DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (ACCOUNT_NO LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
CUSTOMER_NAME VARCHAR(30),
BALANCE DECIMAL(19,4)
);

INSERT INTO ACCOUNT (ACCOUNT_NO, CUSTOMER_NAME, BALANCE) VALUES (0, 'Karen', 1500.00);

DROP TABLE IF EXISTS TRANSACTION_HIST;

CREATE TABLE TRANSACTION_HIST (TIME_STAMP TIMESTAMP NOT NULL, 
ACCOUNT_FROM LONG NOT NULL,
ACCOUNT_TO LONG NOT NULL,
AMOUNT DECIMAL(19,4)
);


INSERT INTO TRANSACTION_HIST (TIME_STAMP, ACCOUNT_FROM, ACCOUNT_TO, AMOUNT) VALUES (CURRENT_TIMESTAMP , 0, 0, 1500.00);